import '../styles/globals.css'

function Nav() {
  return (
    <nav>
      <div className="container nav-inner">
        <a href="/" className="nav-logo">Sedim</a>
        <div className="nav-links">
          <a href="/docs" className="nav-link">Docs</a>
          <a href="https://github.com/Sedimie/Sedim" className="nav-link">GitHub</a>
          <a href="https://discord.com/invite/H7yutstM" className="nav-link" target="_blank">Discord</a>
          <a href="/docs#quick-start" className="btn-nav">Get Started</a>
        </div>
      </div>
    </nav>
  )
}

function Hero() {
  return (
    <section id="hero">
      <div className="container">
        <div className="hero-eyebrow">Open Source -- Zero runtime dependency</div>
        <h1 className="hero-title">
          Boilerplate code.<br />
          <span className="accent">Done right.</span>
        </h1>
        <p className="hero-subtitle">
          Sedim is a CLI that stamps production-ready full-stack features into your codebase. Sessions, OAuth, TOTP, magic links, RBAC -- all yours, fully editable, forever. No SDK, no lock-in.
        </p>
        <div className="hero-install">
          <div className="install-cmd">
            <span className="prefix">$</span>
            <span className="cmd">npm install -g @sedim/cli</span>
          </div>
        </div>
        <div className="hero-actions">
          <a href="/docs" className="btn-primary">Read the docs</a>
          <a href="https://github.com/Sedimie/Sedim" className="btn-secondary" target="_blank">View on GitHub</a>
        </div>
        <p className="hero-note">First module: Auth. Chat, notifications, payments, and more on the roadmap.</p>
      </div>
    </section>
  )
}

function Problem() {
  return (
    <section id="problem">
      <div className="container">
        <div className="problem-grid">
          <div>
            <p className="problem-label">Why Sedim exists</p>
            <h2 className="problem-headline">The 80% gets written over and over.</h2>
            <p className="problem-body">
              Every project starts with the same struggle: implement auth, then chat, then payments -- research the RFCs, pick the right approach, handle the edge cases, update it when new attack vectors emerge. Developers and AI agents alike end up writing different variations of the same code from scratch every time. It is repetitive, time-consuming, and easy to get wrong. Sedim changes that.
            </p>
          </div>
          <ul className="value-list">
            <ValueItem title="You own the stamped code" desc="Files land under src/sedim/. Read them, edit them, customize them. No black box, no runtime dependency." />
            <ValueItem title="Up to date security by default" desc="Argon2id, PKCE S256, TOTP replay protection, magic link non-enumeration. All included, all maintained." />
            <ValueItem title="Framework and ORM agnostic" desc="Next.js, Express, Hono. Drizzle, Prisma. Pair your stack -- Sedim stamps for your exact setup." />
            <ValueItem title="3 UI tiers for every module" desc="Headless, Tailwind-styled, or themed -- just like Shadcn. Customize and ship or use out of the box." />
          </ul>
        </div>
      </div>
    </section>
  )
}

function ValueItem({ title, desc }: { title: string; desc: string }) {
  return (
    <li className="value-item">
      <div className="value-item-check">
        <svg width="10" height="8" viewBox="0 0 10 8" fill="none">
          <path d="M1 3.5L3.5 6L9 1" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      </div>
      <div className="value-item-text">
        <strong>{title}</strong>
        <span>{desc}</span>
      </div>
    </li>
  )
}

function Features() {
  return (
    <section id="features">
      <div className="container">
        <div className="section-header">
          <p className="section-label">What you get</p>
          <h2 className="section-title">Production-grade auth. Stamped in minutes.</h2>
          <p className="section-subtitle">Not a library you import. Not a service you call. Files generated by a CLI that knows your stack.</p>
        </div>
        <div className="features-grid">
          <FeatureCard title="Session-based auth" desc="SHA-256 hashed tokens, httpOnly cookies, full revocation. A real session store -- not a JWT workaround." />
          <FeatureCard title="PKCE OAuth only" desc="RFC 7636 S256 on every OAuth flow. Google, GitHub, Discord. No plain method, ever." />
          <FeatureCard title="TOTP + backup codes" desc="RFC 6238, Google Authenticator compatible. Secrets encrypted at rest with AES-256-GCM." />
          <FeatureCard title="Magic links" desc="Non-enumerating -- always returns success to prevent email discovery. SMTP, Resend, Postmark, SES." />
          <FeatureCard title="RBAC + ABAC" desc="Role-based and attribute-based access control. Middleware factories you apply in your own route files." />
          <FeatureCard title="Rate limiting" desc="Sliding-window rate limiter inline in every operation. In-memory by default, Redis-ready via interface." />
        </div>
      </div>
    </section>
  )
}

function FeatureCard({ title, desc }: { title: string; desc: string }) {
  return (
    <div className="feature-card">
      <div className="feature-icon">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
          <path d="M8 1L10 5.5L15 6L11.5 9.5L12.5 14.5L8 12L3.5 14.5L4.5 9.5L1 6L6 5.5L8 1Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      </div>
      <div className="feature-title">{title}</div>
      <div className="feature-desc">{desc}</div>
    </div>
  )
}

function Roadmap() {
  return (
    <section id="roadmap">
      <div className="container">
        <div className="section-header">
          <p className="section-label">Roadmap</p>
          <h2 className="section-title">More features. Same model.</h2>
          <p className="section-subtitle">Auth is the first module. Everything below is next in line.</p>
        </div>
        <div className="roadmap-grid">
          <RoadmapCard label="01" title="Auth" badge="Active" desc="Redis store, biometric auth, more OAuth providers, more frameworks, more databases." />
          <RoadmapCard label="02" title="Notifications" desc="Email, push, in-app notifications. Multi-channel dispatch with a clean, consistent API." />
          <RoadmapCard label="03" title="Chat" desc="Real-time messaging with WebSocket fallbacks, thread support, presence indicators." />
          <RoadmapCard label="04" title="Payments" desc="Stripe and Paddle integrations. Recurring billing, webhooks, invoice management." />
          <RoadmapCard label="05" title="AI RAG" desc="Retrieval-augmented generation pipelines. Embeddings, vector search, context injection." />
          <RoadmapCard label="06" title="WebRTC" desc="Peer-to-peer video and audio. ICE/STUN/TURN, screen share, and recording." />
        </div>
      </div>
    </section>
  )
}

function RoadmapCard({ label, title, desc, badge }: { label: string; title: string; desc: string; badge?: string }) {
  return (
    <div className="roadmap-card">
      <div className="card-label">Module {label}</div>
      <div className="card-title">{title}</div>
      <div className="card-desc">{desc}</div>
      {badge && <span className="card-status card-status.active">{badge}</span>}
    </div>
  )
}

function HowItWorks() {
  return (
    <section id="how">
      <div className="container">
        <div className="section-header">
          <p className="section-label">How it works</p>
          <h2 className="section-title">Three commands. That is it.</h2>
          <p className="section-subtitle">Sedim detects your stack and stamps only what you need.</p>
        </div>
        <div className="how-steps">
          <HowStep num="1" title="Init" desc="Sedim detects your framework, ORM, and language. Writes a sedim.config.ts." cmd="sedim init" />
          <HowStep num="2" title="Add" desc="Pick features -- email/password, OAuth, TOTP, magic links. See the plan first." cmd="sedim add auth" />
          <HowStep num="3" title="Own" desc="Files land in src/sedim/auth/. You own them, edit them, never look back." cmd="npm run dev" />
        </div>
      </div>
    </section>
  )
}

function HowStep({ num, title, desc, cmd }: { num: string; title: string; desc: string; cmd: string }) {
  return (
    <div className="how-step">
      <div className="step-num">{num}</div>
      <div className="step-title">{title}</div>
      <div className="step-desc">{desc}</div>
      <div className="step-terminal">{cmd}</div>
    </div>
  )
}

function Stacks() {
  return (
    <section id="stacks">
      <div className="container">
        <div className="section-header">
          <p className="section-label">Compatibility</p>
          <h2 className="section-title">Works with your stack</h2>
          <p className="section-subtitle">Framework adapters and ORM adapters. Pick your combination.</p>
        </div>
        <div className="stacks-table">
          <table>
            <thead>
              <tr>
                <th>Framework</th>
                <th>Drizzle</th>
                <th>Prisma</th>
              </tr>
            </thead>
            <tbody>
              <tr><td><strong>Next.js (App Router)</strong></td><td className="check">Supported</td><td className="check">Supported</td></tr>
              <tr><td><strong>Express</strong></td><td className="check">Supported</td><td className="check">Supported</td></tr>
              <tr><td><strong>Hono</strong></td><td className="check">Supported</td><td className="check">Supported</td></tr>
            </tbody>
          </table>
        </div>
        <p style={{ marginTop: '1.5rem', textAlign: 'center', fontSize: '0.875rem', color: 'var(--muted)' }}>
          UI tiers: headless (zero CSS) / Tailwind styled / Themed (CSS tokens)
        </p>
      </div>
    </section>
  )
}

function Contributing() {
  return (
    <section id="contributing">
      <div className="container">
        <div className="section-header">
          <p className="section-label">Community</p>
          <h2 className="section-title">Contributing</h2>
          <p className="section-subtitle">Bug reports, feature additions, framework adapters, documentation -- all welcome.</p>
        </div>
        <div className="contributing-grid">
          <div className="contributing-card">
            <h3>How to contribute</h3>
            <ul>
              <li>Open issues for bugs, feature requests, or questions</li>
              <li>Pick up labeled issues and submit pull requests</li>
              <li>Add framework adapters (SvelteKit, Fastify, etc.)</li>
              <li>Add ORM adapters for unsupported databases</li>
              <li>Improve documentation and examples</li>
              <li>Report security issues to <a href="mailto:security@sedim.dev">security@sedim.dev</a> directly</li>
            </ul>
          </div>
          <div className="contributing-card">
            <h3>Good places to start</h3>
            <ul>
              <li>Issues labeled <a href="https://github.com/Sedimie/Sedim/labels/good%20first%20issue" target="_blank">good first issue</a> -- small, well-bounded tasks</li>
              <li>Issues labeled <a href="https://github.com/Sedimie/Sedim/labels/enhancement" target="_blank">enhancement</a> -- feature extensions to existing modules</li>
              <li>Issues labeled <a href="https://github.com/Sedimie/Sedim/labels/documentation" target="_blank">documentation</a> -- improve docs, add guides</li>
              <li className="discord-link">
                <a href="https://discord.com/invite/H7yutstM" className="discord-btn" target="_blank">
                  <svg width="16" height="12" viewBox="0 0 16 12" fill="none">
                    <path d="M13.5 1a13.3 13.3 0 0 0-3.3-1A9.5 9.5 0 0 0 8 0a9.5 9.5 0 0 0-2.2 1 13.3 13.3 0 0 0-3.3 1A14 14 0 0 0 1 10.2a9.3 9.3 0 0 0 3.4 1.4 6.5 6.5 0 0 0-.3 1.5c0 1.5.8 2.9 1.9 3.7a6.9 6.9 0 0 1-.3 1.2c0 .1-.1.2-.2.2s-.3-.2-.5-.3a11 11 0 0 1-2-2 10 10 0 0 1 1.5-1.4c-.4-.7-.7-1.3-1-1.9-.5.2-.9.3-1.1.3A14 14 0 0 0 13.5 1z" fill="currentColor"/>
                  </svg>
                  Join the Discord
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  )
}

function CTA() {
  return (
    <section id="cta">
      <div className="container">
        <h2 className="cta-title">Skip the repetitive work.</h2>
        <p className="cta-subtitle">AI agents, indie devs, and enterprise teams -- all using the same stamp model. Ship faster, own everything.</p>
        <div className="cta-actions">
          <a href="/docs" className="btn-cta-primary">Read the docs</a>
          <a href="https://github.com/Sedimie/Sedim" className="btn-cta-secondary" target="_blank">View on GitHub</a>
        </div>
      </div>
    </section>
  )
}

function Footer() {
  return (
    <footer>
      <div className="container footer-inner">
        <div className="footer-copy">2026 Sedim -- MIT License</div>
        <div className="footer-links">
          <a href="/docs">Docs</a>
          <a href="https://github.com/Sedimie/Sedim" target="_blank">GitHub</a>
          <a href="https://discord.com/invite/H7yutstM" target="_blank">Discord</a>
        </div>
      </div>
    </footer>
  )
}

export default function Home() {
  return (
    <>
      <Nav />
      <Hero />
      <Problem />
      <Features />
      <Roadmap />
      <HowItWorks />
      <Stacks />
      <Contributing />
      <CTA />
      <Footer />
    </>
  )
}