import path from 'node:path'
import type { DetectedContext, SedimConfig } from '../planning/types'
import { CLI_VERSION, SEDIM_CONFIG_CACHE, SEDIM_CONFIG_FILE } from '../shared/constants'
import { WriteError } from '../shared/errors'
import { writeJSON, writeText } from '../shared/fs'

// builds a SedimConfig from detected context + user choices
export function buildConfig(
  ctx: DetectedContext,
  overrides: Partial<SedimConfig> = {},
): SedimConfig {
  return {
    framework: ctx.framework.value,
    orm: ctx.orm.value,
    db: ctx.db.value,
    language: ctx.language.value,
    moduleSystem: ctx.moduleSystem.value,
    sourceStructure: {
      srcDir: ctx.structure.srcDir,
      apiDir: ctx.codeArchitecture.apiDir,
      routeEntrypoints: ctx.structure.routeEntrypoints,
    },
    preferences: {
      ui: 'headless',
      confirmBeforeWrite: true,
      dryRunByDefault: false,
    },
    overrides: {},
    generatedAt: `${new Date().toISOString()} — sedim v${CLI_VERSION}`,
    ...overrides,
  }
}

export async function writeSedimConfig(projectRoot: string, config: SedimConfig): Promise<void> {
  // write the human-readable sedim.config.ts
  const configTs = renderConfigTemplate(config)
  try {
    await writeText(path.join(projectRoot, SEDIM_CONFIG_FILE), configTs)
    // write the JSON cache for fast programmatic reads
    await writeJSON(path.join(projectRoot, SEDIM_CONFIG_CACHE), config)
  } catch (err) {
    throw new WriteError(`Failed to write sedim.config.ts`, err)
  }
}

function renderConfigTemplate(config: SedimConfig): string {
  return `// sedim.config.ts — generated by sedim v${CLI_VERSION}
// Edit this file to override detection results or set preferences.
// Re-run \`sedim init\` to regenerate from scratch.

import type { SedimConfig } from '@sedim/cli'

const config: SedimConfig = ${JSON.stringify(config, null, 2)}

export default config
`
}
