import path from 'node:path'
import { Project, QuoteKind, VariableDeclarationKind } from 'ts-morph'
import type { DetectedContext, SedimConfig } from '../planning/types'
import { CLI_VERSION, SEDIM_CONFIG_CACHE, SEDIM_CONFIG_FILE } from '../shared/constants'
import { WriteError } from '../shared/errors'
import { writeJSON } from '../shared/fs'

// builds a SedimConfig from detected context + user choices
export function buildConfig(
  ctx: DetectedContext,
  overrides: Partial<SedimConfig> = {},
): SedimConfig {
  return {
    framework: ctx.framework.value,
    orm: ctx.orm.value,
    db: ctx.db.value,
    language: ctx.language.value,
    moduleSystem: ctx.moduleSystem.value,
    sourceStructure: {
      srcDir: ctx.structure.srcDir,
      apiDir: ctx.codeArchitecture.apiDir,
      routeEntrypoints: ctx.structure.routeEntrypoints,
    },
    preferences: {
      ui: 'headless',
      confirmBeforeWrite: true,
      dryRunByDefault: false,
    },
    overrides: {},
    generatedAt: `${new Date().toISOString()} — sedim v${CLI_VERSION}`,
    ...overrides,
  }
}

export async function writeSedimConfig(projectRoot: string, config: SedimConfig): Promise<void> {
  try {
    await writeConfigTs(projectRoot, config)
    await writeJSON(path.join(projectRoot, SEDIM_CONFIG_CACHE), config)
  } catch (err) {
    throw new WriteError(`Failed to write sedim.config.ts`, err)
  }
}

// writes sedim.config.ts as a proper TypeScript object literal using ts-morph
// so the output looks like hand-written TS, not a JSON blob
async function writeConfigTs(projectRoot: string, config: SedimConfig): Promise<void> {
  const project = new Project({
    manipulationSettings: { quoteKind: QuoteKind.Single },
    useInMemoryFileSystem: true,
  })

  const filePath = path.join(projectRoot, SEDIM_CONFIG_FILE)

  const sf = project.createSourceFile('sedim.config.ts', '', { overwrite: true })

  // file header comment
  sf.addStatements(`// sedim.config.ts — generated by sedim v${CLI_VERSION}`)
  sf.addStatements(`// Edit this file to override detection results or set preferences.`)
  sf.addStatements(`// Re-run \`sedim init\` to regenerate from scratch.\n`)

  // import
  sf.addImportDeclaration({
    isTypeOnly: true,
    namedImports: ['SedimConfig'],
    moduleSpecifier: '@sedim/cli',
  })

  sf.addStatements('\n')

  sf.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: 'config',
        type: 'SedimConfig',
        initializer: buildObjectLiteral(config),
      },
    ],
  })

  sf.addStatements('\nexport default config')

  // emit the in-memory file to disk
  const text = sf.getFullText()

  // write via fs-extra directly since we have the final text
  const fsExtra = await import('fs-extra')
  await fsExtra.default.outputFile(filePath, text)
}

// recursively converts a plain object/value into a ts-morph initializer string
// produces clean TS object literals, not JSON (no quoted keys, proper booleans/nulls)
function buildObjectLiteral(value: unknown): string {
  if (value === null) return 'null'
  if (value === undefined) return 'undefined'
  if (typeof value === 'string') return `'${value.replace(/'/g, "\\'")}'`
  if (typeof value === 'boolean' || typeof value === 'number') return String(value)

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    const items = value.map(v => buildObjectLiteral(v)).join(', ')
    return `[${items}]`
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
    if (entries.length === 0) return '{}'
    const props = entries.map(([k, v]) => `  ${k}: ${buildObjectLiteral(v)}`).join(',\n')
    return `{\n${props},\n}`
  }

  return String(value)
}
