export type { AuthConfig, OAuthProviderConfig, OAuthProfile, ResolvedAuthConfig } from './config.js'
export { googleProvider, githubProvider, discordProvider, resolveConfig } from './config.js'
export type { AuthResult, AuthError } from './operations.js'
export { createExpressAuthRouter, createSessionMiddleware, requireAuth as expressRequireAuth } from './express.js'
export { createNextjsAuthHandlers, getSession } from './nextjs.js'
export { createHonoAuthRoutes, createHonoSessionMiddleware, requireAuth as honoRequireAuth } from './hono.js'
