import type { SedimConfig } from '@sedim/cli';

// sedim.config.ts — generated by sedim v0.1.0
// Edit this file to override detection results or set preferences.
// Re-run `sedim init` to regenerate from scratch.
const config: SedimConfig = {
      framework: 'express',
      orm: 'none',
      db: 'postgres',
      language: 'typescript',
      moduleSystem: 'esm',
      sourceStructure: {
      srcDir: 'src',
      apiDir: null,
      routeEntrypoints: [],
    },
      preferences: {
      ui: 'tailwind',
      confirmBeforeWrite: true,
      dryRunByDefault: false,
    },
      overrides: {},
      generatedAt: '2026-05-18T03:22:13.704Z — sedim v0.1.0',
    };

export default config
